# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreateCircle
                                 A QGIS plugin
 Create circle, cenetr defined by latitude and longitude in various formats, radius in various units
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-29
        copyright            : (C) 2018 by Paweł Strzelewicz
        email                : @
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreateCircle class from file CreateCircle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .create_circ import CreateCircle
    return CreateCircle(iface)
